### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by it-is-Aman**
In this pull request, I have made updates to the README file to provide more comprehensive information about this Sigma-Web-Dev-Course .

### CODE REVIEW

**Comment by GauravDe-git** [comment]
Wow Looks good. Hope Harry bhai merges it

**Comment by tamanghawana09** [comment]
Looks clean and also has details to the course, will be of great help for beginners.

**Review by d-coder111 — COMMENTED** [review]
Honestly, this looks great with all the details mentioned into it👍.

**Comment by it-is-Aman** [comment]
> Wow Looks good. Hope Harry bhai merges it

Thanks Gaurav, Let's see when Harry bhai merges it

**Comment by GauravDe-git** [comment]
Btw I was hoping if there would be an Official Code With Harry Discord server, then it would be so cool, to be able to interact with the community. Can you we make a petition for an official Code With Harry Discord 😢

**Comment by d-coder111** [comment]
> Btw I was hoping if there would be an Official Code With Harry Discord server, then it would be so cool, to be able to interact with the community. Can you we make a petition for an official Code With Harry Discord 😢

I think that would be an amazing idea to help and collaborate with each other because we are learning from harry bhai's latest course so we could help with each other's errors in the code and learn together👍😊

**Comment by it-is-Aman** [comment]
@tamanghawana09 Thanks for the positive feedback!
@d-coder111 Glad you liked this

**Comment by it-is-Aman** [comment]
> Btw I was hoping if there would be an Official Code With Harry Discord server, then it would be so cool, to be able to interact with the community. Can you we make a petition for an official Code With Harry Discord 😢

It would be great if we could find a coding buddy in Harry Discord server to learn together and help each other solve errors.

**Comment by Sagar05Attri** [comment]
> > Btw I was hoping if there would be an Official Code With Harry Discord server, then it would be so cool, to be able to interact with the community. Can you we make a petition for an official Code With Harry Discord 😢
> 
> I think that would be an amazing idea to help and collaborate with each other because we are learning from harry bhai's latest course so we could help with each other's errors in the code and learn together👍😊

yes we all should also connect with each other.. please let me know if you guys do this...

**Comment by adnanAliSDE** [comment]
Please also add a link to the course playlist in the readme:

**Review by Atharva1723 — APPROVED** [review]

**Review by Krishna-Singhal — APPROVED** [review]

**Review by Krishna-Singhal — APPROVED** [review]

**Comment by Alan-Abdul-Kalaam-25** [comment]
It's seems to be a useful README.md, Harry bro should consider to merge it to help others access the SIGMA OP course.

**Review by kushwahankit — COMMENTED** [review]
👍👍👍👍❤️❤️❤️❤️

**Review by Alan-Abdul-Kalaam-25 — APPROVED** [review]

**Pull request merged**
